apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  # Use base64 encoded values for sensitive data
  ADMIN_PASSWORD: YWRtaW5wYXNz  # adminpass
  DB_PASSWORD: cGFzc3dvcmQ=  # password (this is base64 encoded)