apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkBsb2NhbGhvc3Q6NTQzMi9ub3RpZmljYXRpb25fc2VydmljZV9kYj9zc2xtb2RlPWRpc2FibGU=  # base64 encoded