apiVersion: v1
kind: Secret
metadata:
  name: permission-service-secrets
type: Opaque
data:
  DB_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkBsb2NhbGhvc3Q6NTQzMi9wZXJtaXNzaW9uX3NlcnZpY2VfZGI/c3NsbW9kZT1kaXNhYmxl  # base64 encoded DB_URL