apiVersion: v1
kind: Service
metadata:
  name: file-picker-service
spec:
  type: ClusterIP  # Correct for internal service
  selector:
    app: file-picker
  ports:
    - protocol: TCP
      port: 80        # External port exposed
      targetPort: 8080  # Should match the container's port