# Default values for notification-service.

replicaCount: 3  # Set the replica count to 3

image:
  repository: notification  # Use the notification-service image
  pullPolicy: IfNotPresent
  # Set the image tag for the notification service
  tag: v1

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - name: websocket
      port: 50054  # WebSocket port
      targetPort: 50054
      protocol: TCP
    - name: grpc
      port: 50055  # gRPC port
      targetPort: 50055
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: notification-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health  # This assumes you have a /health endpoint
    port: 50054    # WebSocket port for health check
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health  # This assumes you have a /health endpoint
    port: 50054    # WebSocket port for readiness check
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}