apiVersion: v1
kind: Secret
metadata:
  name: file-downloader-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBsb2NhbGhvc3Q6NTQzMi9maWxlZG93bmxvYWRlcmRiP3NzbG1vZGU9ZGlzYWJsZQ==