apiVersion: v1
kind: Service
metadata:
  name: file-downloader-service
spec:
  type: ClusterIP
  selector:
    app: downloader
  ports:
    - protocol: TCP
      port: 8080       # Expose port 8080
      targetPort: 8080 # Target the same internal port