apiVersion: v1
kind: Service
metadata:
  name: file-transformation-service
spec:
  type: ClusterIP
  selector:
    app: file-transformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080