apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: permissions-verification-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: permission
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]