apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-verification
  namespace: default
spec:
  selector:
    matchLabels:
      app: file-picker
  jwtRules:
  - issuer: {{ .Values.auth.issuer }}
    forwardOriginalToken: True
    jwks: #include your public key here
      