apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: downloader-vs
  namespace: default
spec:
  hosts:
  - downloader.default.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: # TODO : define API -> /download
    route:
    - destination:
        host: downloader.default.svc.cluster.local
        port:
          number: 80
