apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: file-picker-vs
  namespace: default
spec:
  hosts:
  - file-picker-service.default.svc.cluster.local
  gateways:
  - public-gateway
  http:
  - match:
    - uri:
        prefix: /file-picker
    route:
    - destination:
        host: file-picker-service.default.svc.cluster.local
        port:
          number: 80