apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: file-transformation-vs
  namespace: default
spec:
  hosts:
  - file-transformation-service.default.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: # TODO : define API /file-transform
    route:
    - destination:
        host: file-transformation-service.default.svc.cluster.local
        port:
          number: 80