apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: permissions-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
  - match:
    - uri:
        prefix: /add_user
    route:
    - destination:
        host: permissions.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /delete_user
    route:
    - destination:
        host: permissions.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /add_group
    route:
    - destination:
        host: permissions.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /delete_group
    route:
    - destination:
        host: permissions.default.svc.cluster.local
        port:
          number: 80